HOST: '10.252.101.139'
GPU_DECOMPRESSION: True # True: NvJpeg, False: TurboJPEG
IMAGE_SHOW: True

PORT:
  STEREO_L: 5001
  STEREO_R: 5002
  RGBD: 5003
  DETECTION: 5050
  MONO_DEPTH: 5052

SW_INFO:
  STEREO_L: True
  STEREO_R: True
  RGBD: True
  DETECTION: True
  MONO_DEPTH: True